export const LOADING = 'LOADING';
export const RESPONSE_PET_LIST_SUCCESS = 'RESPONSE_PET_LIST_SUCCESS'
export const RESPONSE_PET_LIST_BY_LOCATION_SUCCESS = 'RESPONSE_PET_LIST_BY_LOCATION_SUCCESS';
export const ERROR = 'ERROR';