export const SIGN_UP_BY_VERTIFICATION_CODE_SUCCESS =
  'SIGN_UP_BY_VERTIFICATION_CODE_SUCCESS';
export const LOADING = 'LOADING';
export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
