export const RESPONSE_PET_DETAIL_SUCCESS = 'RESPONSE_PET_DETAIL_SUCCESS';
export const RESPONSE_PET_DETAIL_ERROR = 'RESPONSE_PET_DETAIL_ERROR';
export const RESPONSE_COMMENT_LIST_SUMMARY = 'RESPONSE_COMMENT_LIST_SUMMARY';
export const RESPONSE_COMMENT_LIST = 'RESPONSE_COMMENT_LIST';
export const RESPONSE_COMMENT_LIST_ERROR = 'RESPONSE_COMMENT_LIST_ERROR';
export const LOADING = 'LOADING';
